version: '2'
services:
  web-sample:
    build: .
    volumes:
      - .:/project-anima
    ports:
      - "8081:8080"
    container_name: web-sample
  nginx-sample:
    build: ./docker/nginx
    ports:
       - "8083:80"
    restart: always
    links:
        - web-sample
    container_name: nginx-sample
